### ISSUE TITLE
I want to retrieve data in nrf52840 .

### ISSUE THREAD

**Issue by mohsin485** [mokhwasomssi/stm32_hal_icm20948#1]
I have been doing efforts to do the same thing on NRF52840 with I2C , I have configured every register right but not get the desired data , It is giving me same value again and again and value is not changing at any time , Can you please help to me in that . Thanks in advance .This is code and its showing logs like that . [
[code icm20948.txt](https://github.com/mokhwasomssi/stm32_hal_icm20948/files/7121105/code.icm20948.txt)
[logs.txt](https://github.com/mokhwasomssi/stm32_hal_icm20948/files/7121106/logs.txt)
](url)

**Comment by mokhwasomssi** [comment]
## TWI TX sequence

### Your code in `ICM()` function

```c
uint8_t reg4[2]={B0_pwr_management,0xB0};
err_code = nrf_drv_twi_tx(&m_twi, B0_pwr_management,reg4,2, false);
```

### Right code I think (i haven't use nrf driver)

```c
uint8_t reg4[2]={B0_pwr_management,0xB0};
// put ICM20948addr instead of B0_pwr_management
err_code = nrf_drv_twi_tx(&m_twi, ICM20948addr, reg4,2, false); 
```

## TWI RX sequence

### Your code in `read_gyro()` function
```c
ret_code_t err_code = nrf_drv_twi_rx(&m_twi, ICM20948addr , temp , 6);
```

### Right code I think (i haven't use nrf driver)

```c
uint8_t reg_addr = B0_GYRO_XOUT_H;

err_code = nrf_drv_twi_tx(&m_twi, ICM20948addr, &reg_addr, 1); // first, transmit register address
APP_ERROR_CHECK(err_code);

err_code = nrf_drv_twi_rx(&m_twi, ICM20948addr, temp, 6); // and receive register value
APP_ERROR_CHECK(err_code);
```

**Comment by mohsin485** [comment]
I have done these things 
please tell me what do you mean by register default values .
secondly if i am doing it on i2c , Am i suppose to on any register bit or it automatically detect that its I2C .
I am doing the procedure as i am sending register address and value to icm address , Is that the right way or i have to send value only to register not through ICM .

**Comment by mokhwasomssi** [comment]
did you read datasheet?

**Comment by mohsin485** [comment]
Yes i read it , Did you mean reset value by default value ?

**Comment by mokhwasomssi** [comment]
Sorry, I explained it(I recommend this process...) wrong. forget it.
If you set `DEVICE_RESET` bit in PWR_MGMT_1, all register have reset value.
So, you don't have to put reset value in each register.

And, to be honest, I couldn't understand what you're asking. 😥

**Comment by mohsin485** [comment]
uint8_t reg4[2]={B0_pwr_management,0xB0};
// put ICM20948addr instead of B0_pwr_management
err_code = nrf_drv_twi_tx(&m_twi, ICM20948addr, reg4,2, false);  

I am asking as i am doing in this code sending register address and value to address of ICM20948 (0X68) , Is that the right procedure .

**Comment by mohsin485** [comment]
I want to ask another question that is 
is this code working fine on your controller ?

**Comment by mokhwasomssi** [comment]
Yes, it is right procedure. 

I2C has only 2 wire. 
So master have to send slave address at the first of communication to select slave you want to communcate.
![image](https://user-images.githubusercontent.com/48342925/132486395-575b06e5-c0eb-440a-86f1-92eb86eaad25.png)

This is i2c Read/Write sequence.
![image](https://user-images.githubusercontent.com/48342925/132488273-fdff825a-2a1a-4759-917f-3cda57999525.png)

As you can see, the second parameter is address of slave device.
<img src = "https://user-images.githubusercontent.com/48342925/132487225-f222f1b9-73d5-41c0-8530-2423cd820a7d.png" width = "80%" height = "80%">

**Comment by mokhwasomssi** [comment]
This code working fine on stm32f4 controller

In this video, I calculated drone angle using icm20948 gyro and accel data.
https://youtu.be/Yh-hQLEkqXM

**Comment by mohsin485** [comment]
Hello again , 
I make read write function separately reading all register giving me just right value except b0_control reg of bank 0 and B0_EXT_SLV_SENS_DATA_00 , B0_EXT_SLV_SENS_DATA_00 giving me zero value again and again , I am just verifying whoiam of magnetometer . I am adding all codes here please give a small review on that .

static void magnetometer()
{
select_bank(0);
read_data(0,B0_USER_CTRL);
write_data(0,B0_USER_CTRL,0x22,2);
read_data(0,B0_USER_CTRL);
write_data(0,B0_USER_CTRL,0x22,2);
read_data(3,B3_I2C_MST_CTRL);
write_data(3,B3_I2C_MST_CTRL,0x07,2);
read_data(3,B3_I2C_MST_CTRL);
write_data(3,B3_I2C_SLV0_ADDR,0x8C,2);
read_data(3,B3_I2C_SLV0_ADDR);
write_data(3,B3_I2C_SLV0_REG,0x01,2);
read_data(3,B3_I2C_SLV0_REG);
write_data(3,B3_I2C_MST_CTRL,0x81,2);
read_data(3,B3_I2C_MST_CTRL);
nrf_delay_ms(10);
select_bank(0);
read_data(0,B0_EXT_SLV_SENS_DATA_00);
}
void write_data(uint8_t ub , uint8_t regaddress , uint8_t regdata , uint8_t size)
{
writeregaddress=regaddress;
writeregdata=regdata;
len = size;
writeub=ub;
nrf_delay_ms(10);
select_bank(writeub);
nrf_delay_ms(10);
uint8_t writedata[2] = {writeregaddress , writeregdata};
err_code = nrf_drv_twi_tx(&m_twi, ICM20948addr ,writedata,len, true);
APP_ERROR_CHECK(err_code);
}

void read_data(uint8_t ub , uint8_t regaddress)
{
writeub=ub;
readregaddress=regaddress;
nrf_delay_ms(10);
select_bank(writeub);
nrf_delay_ms(10);
err_code = nrf_drv_twi_tx(&m_twi, ICM20948addr ,&readregaddress,1, true);
APP_ERROR_CHECK(err_code);
nrf_delay_ms(10);
read_sensor_data();
}

void select_bank(uint8_t bankselectvalue)
{
funbankselect=bankselectvalue;
shifted_value=funbankselect<<4;
bank[0]=bankselect;
bank[1]=shifted_value;
err_code = nrf_drv_twi_tx(&m_twi, ICM20948addr,bank,2, false);
APP_ERROR_CHECK(err_code);
}

void read_sensor_data()
{
    m_xfer_done = false;
    //NRF_LOG_INFO("1");
    //NRF_LOG_FLUSH();
    
    /* Read 1 byte from the specified address - skip 3 bits dedicated for fractional part of temperature. */
    ret_code_t err_code = nrf_drv_twi_rx(&m_twi,ICM20948addr  ,& m_sample, 1);
    APP_ERROR_CHECK(err_code);
    NRF_LOG_INFO("%x",m_sample);
    NRF_LOG_FLUSH();
    
}

int main()
{
    APP_ERROR_CHECK(NRF_LOG_INIT(NULL));
    NRF_LOG_DEFAULT_BACKENDS_INIT();
    NRF_LOG_INFO("\r\nTWI sensor example started.");
    NRF_LOG_FLUSH();
    twi_init();
    NRF_LOG_INFO("1");
    NRF_LOG_FLUSH();
    //ICM();
    magnetometer();
    NRF_LOG_INFO("end icm");
    

    
    NRF_LOG_FLUSH();
    }

and these are logs 

<info> app: 
TWI sensor example started.
<info> app: 1
<info> app: 0
<info> app: Register value = 32 
<info> app: 20
<info> app: Register value = 32 
<info> app: 20
<info> app: Register value = 129 
<info> app: 81
<info> app: Register value = 7 
<info> app: 7
<info> app: Register value = 140 
<info> app: 8C
<info> app: Register value = 1 
<info> app: 1
<info> app: Register value = 129 
<info> app: 81
<info> app: Register value = 0 
<info> app: end icm

please reply , Thanks in advance.
